default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username:
  password:
  host: localhost

development:
  <<: *default
  database: physio_jobs_dev

test:
  <<: *default
  database: physio_jobs_test
